### ISSUE TITLE
Make bar start after navbar

### ISSUE THREAD

**Issue by ghost** [mburakerman/prognroll#3]
If i have an xem height navbar at the top, how would i make the bar start gaining width AFTER the user scrolls past it?

Thank you,

**Comment by mburakerman** [comment]
Prognroll prepend a `span `to body to show progress bar. 
[Here](https://github.com/mburakerman/prognroll/blob/master/src/prognroll.js#L42), i change width of the `span` _( `bar `class_) as user scroll. So, you can play with that code and put your `navbar` instead of `span`.
